version: '3'


services:
  db:
    image: postgres:latest
    container_name: test_car_db
    environment:
      - POSTGRES_DB=car
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '8081:5432'